// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProspectStudio.Infrastructure.Storage;

#nullable disable

namespace ProspectStudio.Infrastructure.Storage.Migrations
{
    [DbContext(typeof(ProspectDbContext))]
    partial class ProspectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ProspectStudio.Core.Domain.Campaign", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_path");

                    b.Property<string>("GeoJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("geo_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Product")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("product");

                    b.Property<string>("ProfileJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_json");

                    b.Property<DateTime?>("ProfileSavedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_saved_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_campaigns_slug");

                    b.ToTable("campaigns", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
