<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ProspectStudio.Infrastructure</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProspectStudio.Core\ProspectStudio.Core.csproj" />
  </ItemGroup>

</Project>
